<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
 ?>
<script>
require([
    "prototype",
    "Magento_Sales/order/create/form",
    "Magento_Catalog/catalog/product/composite/configure",
    "domReady!"
], function(){

    order.sidebarHide();
    if (window.productConfigure) {
        productConfigure.addListType('product_to_add', {
            urlFetch: '<?php /* @escapeNotVerified */ echo $block->getUrl('quotation/quote_create/configureProductToAdd') ?>'
        });
        productConfigure.addListType('quote_items', {
            urlFetch: '<?php /* @escapeNotVerified */ echo $block->getUrl('quotation/quote_create/configureQuoteItems') ?>'
        });
    }

});
</script>